### ISSUE TITLE
Wrong pkctr

### ISSUE THREAD

**Issue by keomabrun** [openwsn-berkeley/mercator#11]
When looking at the logs, we can observe lines like this one:
```
timestamp,mac,frequency,length,rssi,crc,expected,srcmac,transctr,pkctr,txnumpk,txpower,txifdur,txlength,txfillbyte
2016-10-17_18.45.41,05-43-32-ff-03-df-93-67,11,100,-91,0,0,05-43-32-ff-03-db-c3-68,1,4129,10,0,100,100,0x0a
```
4129 is not valid as only 10 pkts are sent.

**Comment by twatteyne** [comment]
:-(
Parsing problem?

**Comment by ddujovne** [comment]
Counter reset problem?

**Comment by keomabrun** [comment]
My bad. CRC is 0, meaning that the CRC is wrong.
``expected`` byte is 0 too, meaning that the packet was not expected.

This is just a value replacement error as the documentation says for the ``pkctr`` field: 
`Set to all 0's if crc or expected is 0.`

**Comment by twatteyne** [comment]
cool. good catch.
