### ISSUE TITLE
Device is not accessible after TXDONE

### ISSUE THREAD

**Issue by keomabrun** [openwsn-berkeley/mercator#2]
### setup

Two OpenMotes running the latest firmware

### issue

After telling a device to send, it stops responding to further commands.

### to reproduce

```
> rx /dev/ttyUSB0
> tx /dev/ttyUSB1
```

After a few seconds:

```
    `type             : IND_TXDONE`
> st /dev/ttyUSB0
`{'status': 4, 'type': 2, 'mac': (0, 18, 75, 0, 6, 13, 158, 223), 'numnotifications': 0}`
> st /dev/ttyUSB1
---------------------------/dev/ttyUSB1
None
```

**Comment by twatteyne** [comment]
@keomabrun, thanks for catching this. What hardware are you using?

**Comment by twatteyne** [comment]
I have reworked the issue description, and realize you specified that. Which firmware are you running? Latest from the `openwsn-fw` develop branch?

**Comment by keomabrun** [comment]
Yes, the latest from openwsn-fw, with the oos_mercator project.

**Comment by keomabrun** [comment]
Error was fixed on firmware side.
