### ISSUE TITLE
add pdr over time over frequency script and datasets

### ISSUE THREAD

**Issue by keomabrun** [openwsn-berkeley/mercator#26]

**Comment by keomabrun** [comment]
PDR over time makes no sense as it will reflect PDR over freq.

**Comment by twatteyne** [comment]
we still would like to be able to see PDR vs. time vs. freq, no?

**Comment by twatteyne** [comment]
well, it will show us the variability of a wireless link over time on a particular frequency, allowing us to compare a single-frequency link with the case where we are channel hopping over multiple/all frequencies

**Comment by keomabrun** [comment]
yes. I agree. see my response in https://github.com/openwsn-berkeley/mercator/issues/27#issuecomment-270599767
