### ISSUE TITLE
add rssi over time over frequency script and datasets

### ISSUE THREAD

**Issue by keomabrun** [openwsn-berkeley/mercator#27]

**Comment by keomabrun** [comment]
RSSI over time makes no sense as it will reflect RSSI over freq.

**Comment by twatteyne** [comment]
same here, don't we want to be able to see the variation over time of the RSSI for a particular frequency?

**Comment by keomabrun** [comment]
alright I get it now. Indeed we want that.
Current we haven't considered results that are not relative to one emitter.
