### ISSUE TITLE
One connection refused crashes the experiment

### ISSUE THREAD

**Issue by keomabrun** [openwsn-berkeley/mercator#3]
When the app is no able to connect with a mote, it crashes the entire experiment.

Should we force the app to continue ? (we can make this feature an option)

The following error is raised:
```
could not connect to m3-291, reason: [Errno 111] Connection refused
Traceback (most recent call last): 
  File "mercatorRunExperiment.py", line 283, in <module>
    main()
  File "mercatorRunExperiment.py", line 279, in main
    site = site
  File "mercatorRunExperiment.py", line 56, in __init__
    self.motes[s]    = MoteHandler.MoteHandler(s,self._cb)
  File "/senslab/users/brun/mercator/code/software/app/../lib/MoteHandler.py", line 45, in __init__
    raise SystemError(msg)
SystemError: could not connect to m3-291, reason: [Errno 111] Connection refused
```

**Comment by twatteyne** [comment]
IMO, doesn't make sense to continue the experiment.

**Comment by keomabrun** [comment]
Thanks for the quick answer.
I'll try to see if we can blacklist error prone nodes.

**Comment by twatteyne** [comment]
I believe a good approach would be to write a separate utility which scans for dead motes, without including that functionality in the main `mercator` tool.

**Comment by keomabrun** [comment]
It depends if we want to run it onces or before every experiment.

**Comment by twatteyne** [comment]
flagging the broken motes is an IoT-lab thing.
One can run mercator on any testbed, not just IoT-lab,
The two things should be different.

**Comment by ddujovne** [comment]
As long as the motes keep working during the experiment, an initial check is fine. Last time, when we worked with the WSN430 nodes, although communication was verified at the beginning, they failed during the experiment.

**Comment by keomabrun** [comment]
:+1:
